### ISSUE TITLE
Watchdog crash on KeyError: 'last_received_message'

### ISSUE THREAD

**Issue by abramov-oleg** [insight-platform/PipelineWatchdog#4]
### Reproduce

1. `docker compose -f samples/pipeline_monitoring/docker-compose.yml up --build -d`
2. `docker logs -f pipeline-watchdog`

Pipeline watchdog container logs

```
2024-08-21 03:06:23 INFO Watching buffer metrics 127.0.0.1:8000
Traceback (most recent call last):
  File "/app/src/pipeline_watchdog/run.py", line 195, in <module>
    main()
  File "/app/src/pipeline_watchdog/run.py", line 186, in main
    loop.run_until_complete(futures)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/src/pipeline_watchdog/run.py", line 152, in watch_buffer
    await asyncio.gather(
  File "/app/src/pipeline_watchdog/run.py", line 137, in watch_ingress
    last_received_message = metrics[LAST_RECEIVED_MESSAGE_METRIC]
KeyError: 'last_received_message'
```

then crashes and is restarted by the docker compose. 

The `pipeline_monitoring-client-1` container **doesn't** print

```
Traceback (most recent call last):
  File "/opt/savant/src/client.py", line 52, in <module>
    main()
  File "/opt/savant/src/client.py", line 37, in main
    time.sleep(sleep_duration)
KeyboardInterrupt
```

**Comment by abramov-oleg** [comment]
Does not reproduce after updating  `ghcr.io/insight-platform/savant-adapters-py:latest` to digest `sha256:979aec81d0befb5b72bdbf4ce50ce0813e20fc56166f61d716b4899afd5881cf`
